# Generated by Django 5.1.6 on 2025-02-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='date',
        ),
    ]
